version: "3.5"

services:

  react-app:
    container_name: api_node
    build: .
    image: colmedo/apinode
    networks: 
      - web    
    volumes:
      - node_modules:/api
    labels:
      - "traefik.enable=true"
      - "traefik.port=4000"
      - "traefik.frontend.rule=Host:api.carlosdev.fr"
      - "traefik.docker.network=web"

networks:
  web:
    external: true  

volumes: 
  node_modules: